export const transferRumorsCopy = {
  pageTitle: "Φήμες Μεταγραφών",
  teamPageTitle: (teamName: string) => `Φήμες Μεταγραφών — ${teamName}`,
  hubSubtitle: "Επιλέξτε ομάδα ή υποβάλετε μια φήμη μεταγραφής.",
  leagueTabsAriaLabel: "Επιλογή πρωταθλήματος",
  teamGridAriaLabel: "Επιλογή ομάδας",
  empty: "Δεν υπάρχουν φήμες μεταγραφών ακόμα.",
  emptyHint: "Ξεκινήστε μια συζήτηση για τις μεταγραφές που ακούτε.",
  listAriaLabel: "Λίστα φήμων μεταγραφών",
  crossLinkTransfers: "Δείτε τις επίσημες μεταγραφές",
  backToHub: (leagueName: string) => `Όλες οι ομάδες — ${leagueName}`,
  mustBeSignedIn: "Πρέπει να συνδεθείτε για να υποβάλετε φήμη.",
  needFanProfile: "Χρειάζεστε fan profile για αυτό το πρωτάθλημα.",
  genericError: "Η υποβολή απέτυχε. Δοκιμάστε ξανά.",
  form: {
    sectionAriaLabel: "Υποβολή φήμης μεταγραφής",
    heading: "Νέα φήμη",
    teamLabel: "Ομάδα",
    teamPlaceholder: "Επιλέξτε ομάδα",
    titleLabel: "Τίτλος",
    titlePlaceholder: "π.χ. Ενδιαφέρον για νέο επιθετικό",
    bodyLabel: "Περιγραφή",
    bodyPlaceholder: "Τι ακούτε; Πηγή ή λεπτομέρειες…",
    submit: "Υποβολή φήμης",
    submitting: "Υποβολή…",
    signInPrompt: "Συνδεθείτε για να υποβάλετε φήμη.",
    signInLink: "Σύνδεση",
    fanProfilePrompt: "Δημιουργήστε fan profile για αυτό το πρωτάθλημα.",
    fanProfileLink: "Fan profile",
  },
} as const;
