/**
 * Mock data — replace when feed is wired to DB/API.
 */

import type {
  FeedLeague,
  FeedMatch,
  FeedThread,
  StandingRow,
  TrendingThread,
  UpcomingMatch,
} from "@/components/feed/feed-data";

export const mockFeedLeagues: FeedLeague[] = [
  { slug: "super-league", name: "Super League", emoji: "⚽" },
  { slug: "champions-league", name: "Champions League", emoji: "⭐" },
  { slug: "premier-league", name: "Premier League", emoji: "⚽" },
  { slug: "euroleague", name: "Euroleague", emoji: "🏀" },
  { slug: "nba", name: "NBA", emoji: "🏀" },
];

export const mockFeedMatches: FeedMatch[] = [
  {
    id: "m1",
    homeTeam: "Παναθηναϊκός",
    awayTeam: "Ολυμπιακός",
    homeScore: 1,
    awayScore: 1,
    status: "live",
    leagueSlug: "super-league",
    leagueName: "Super League",
    minute: "67'",
  },
  {
    id: "m2",
    homeTeam: "ΑΕΚ",
    awayTeam: "ΠΑΟΚ",
    homeScore: 2,
    awayScore: 0,
    status: "live",
    leagueSlug: "super-league",
    leagueName: "Super League",
    minute: "82'",
  },
  {
    id: "m3",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    status: "upcoming",
    leagueSlug: "premier-league",
    leagueName: "Premier League",
    kickoffTime: "21:45",
  },
  {
    id: "m4",
    homeTeam: "Real Madrid",
    awayTeam: "Barcelona",
    homeScore: 3,
    awayScore: 2,
    status: "finished",
    leagueSlug: "champions-league",
    leagueName: "Champions League",
  },
  {
    id: "m5",
    homeTeam: "Ολυμπιακός",
    awayTeam: "Παναθηναϊκός",
    status: "upcoming",
    leagueSlug: "euroleague",
    leagueName: "Euroleague",
    kickoffTime: "20:30",
  },
];

export const mockFeedThreads: FeedThread[] = [
  {
    id: 42,
    slug: "panathinaikos-olympiakos-live",
    title: "Παναθηναϊκός vs Ολυμπιακός — Live συζήτηση",
    leagueSlug: "super-league",
    leagueName: "Super League",
    type: "match_thread",
    isLive: true,
    authorName: "GreenEagle_Pao",
    authorInitials: "GE",
    replyCount: 847,
    lastActivity: "τώρα",
  },
  {
    id: 38,
    slug: "aek-paok-preview",
    title: "ΑΕΚ vs ΠΑΟΚ — Προεπισκόπηση & προβλέψεις",
    leagueSlug: "super-league",
    leagueName: "Super League",
    type: "match_thread",
    isLive: true,
    authorName: "YellowDevil",
    authorInitials: "YD",
    replyCount: 312,
    lastActivity: "2λ",
  },
  {
    id: 35,
    slug: "transfer-rumors-january",
    title: "Μεταγραφές Ιανουαρίου — τι ακούτε;",
    leagueSlug: "super-league",
    leagueName: "Super League",
    type: "discussion",
    isLive: false,
    authorName: "TransferGuru",
    authorInitials: "TG",
    replyCount: 156,
    lastActivity: "8λ",
  },
  {
    id: 31,
    slug: "arsenal-chelsea-preview",
    title: "Arsenal vs Chelsea — Pre-match thread",
    leagueSlug: "premier-league",
    leagueName: "Premier League",
    type: "match_thread",
    isLive: false,
    authorName: "GunnersGR",
    authorInitials: "GG",
    replyCount: 89,
    lastActivity: "15λ",
  },
  {
    id: 28,
    slug: "champions-league-draw",
    title: "Κλήρωση Champions League — αντιδράσεις",
    leagueSlug: "champions-league",
    leagueName: "Champions League",
    type: "news",
    isLive: false,
    authorName: "UCLFan",
    authorInitials: "UF",
    replyCount: 234,
    lastActivity: "22λ",
  },
  {
    id: 25,
    slug: "euroleague-olympiakos-panathinaikos",
    title: "Ολυμπιακός vs Παναθηναϊκός — Euroleague derby",
    leagueSlug: "euroleague",
    leagueName: "Euroleague",
    type: "match_thread",
    isLive: false,
    authorName: "RedDevil7",
    authorInitials: "RD",
    replyCount: 178,
    lastActivity: "35λ",
  },
  {
    id: 22,
    slug: "nba-lakers-celtics",
    title: "Lakers vs Celtics — Game thread",
    leagueSlug: "nba",
    leagueName: "NBA",
    type: "match_thread",
    isLive: false,
    authorName: "HoopsGR",
    authorInitials: "HG",
    replyCount: 67,
    lastActivity: "1ώ",
  },
  {
    id: 19,
    slug: "poll-best-stadium",
    title: "Ποιο είναι το καλύτερο γήπεδο στην Ελλάδα;",
    leagueSlug: "super-league",
    leagueName: "Super League",
    type: "poll",
    isLive: false,
    authorName: "StadiumHopper",
    authorInitials: "SH",
    replyCount: 445,
    lastActivity: "2ώ",
  },
  {
    id: 15,
    slug: "referee-decisions-week-12",
    title: "Αποφάσεις διαιτητών — 12η αγωνιστική",
    leagueSlug: "super-league",
    leagueName: "Super League",
    type: "discussion",
    isLive: false,
    authorName: "FairPlay",
    authorInitials: "FP",
    replyCount: 523,
    lastActivity: "3ώ",
  },
  {
    id: 12,
    slug: "premier-league-title-race",
    title: "Premier League title race — ποιος θα το πάρει;",
    leagueSlug: "premier-league",
    leagueName: "Premier League",
    type: "discussion",
    isLive: false,
    authorName: "EPLWatcher",
    authorInitials: "EW",
    replyCount: 198,
    lastActivity: "4ώ",
  },
];

export const mockStandings: StandingRow[] = [
  { rank: 1, team: "Ολυμπιακός", points: 38 },
  { rank: 2, team: "Παναθηναϊκός", points: 35 },
  { rank: 3, team: "ΑΕΚ", points: 33 },
  { rank: 4, team: "ΠΑΟΚ", points: 30 },
  { rank: 5, team: "Αρης", points: 25 },
];

export const mockUpcomingMatches: UpcomingMatch[] = [
  {
    id: "u1",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    kickoffTime: "Σήμερα 21:45",
    leagueName: "Premier League",
  },
  {
    id: "u2",
    homeTeam: "Ολυμπιακός",
    awayTeam: "Παναθηναϊκός",
    kickoffTime: "Αύριο 20:30",
    leagueName: "Euroleague",
  },
  {
    id: "u3",
    homeTeam: "Αστέρας",
    awayTeam: "Λαμία",
    kickoffTime: "Κυρ 18:00",
    leagueName: "Super League",
  },
];

export const mockTrendingThreads: TrendingThread[] = [
  {
    id: 42,
    slug: "panathinaikos-olympiakos-live",
    title: "Παναθηναϊκός vs Ολυμπιακός — Live",
    leagueSlug: "super-league",
    replyCount: 847,
  },
  {
    id: 19,
    slug: "poll-best-stadium",
    title: "Ποιο είναι το καλύτερο γήπεδο;",
    leagueSlug: "super-league",
    replyCount: 445,
  },
  {
    id: 15,
    slug: "referee-decisions-week-12",
    title: "Αποφάσεις διαιτητών — 12η αγωνιστική",
    leagueSlug: "super-league",
    replyCount: 523,
  },
];
